Clarama:
  AI:
    Profile:
      Default:
        Summary: gemma3:1b
        Python: codellama:python
        SQL: sqlcoder:7b
        Influx: gemma3:4a
        Mermaid: gemma3:1b
        Math: qwen2-math
